version: "3"
services:
  orders-db:
    container_name: coding-interview
    image: postgres:15.3
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5446:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=coding-level-3
